<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOvaxPk1\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOvaxPk1/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerOvaxPk1.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerOvaxPk1\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerOvaxPk1\appAppKernelProdContainer([
    'container.build_hash' => 'OvaxPk1',
    'container.build_id' => '39fc80d3',
    'container.build_time' => 1768996830,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOvaxPk1');
